//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFPIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kvar
    {
        public int KvarID { get; set; }
        public System.DateTime DatumKvara { get; set; }
        public String Datum { get; set; }
        public string OpisKvara { get; set; }
        public int IDZaposlenog { get; set; }
        public int GostID { get; set; }
        public int BrojSobe { get; set; }
    
        public virtual Gost Gost { get; set; }
        public virtual Soba Soba { get; set; }
        public virtual Zaposleni Zaposleni { get; set; }
    }
}
