//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFPIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaParkGateEntities : DbContext
    {
        public BazaParkGateEntities()
            : base("name=BazaParkGateEntities")
        {
            base.Configuration.ProxyCreationEnabled = false;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gost> Gost { get; set; }
        public virtual DbSet<Kvar> Kvar { get; set; }
        public virtual DbSet<Rezervacija> Rezervacija { get; set; }
        public virtual DbSet<Soba> Soba { get; set; }
        public virtual DbSet<StavkaZahtevaZaDodatneUsluge> StavkaZahtevaZaDodatneUsluge { get; set; }
        public virtual DbSet<ZahtevZaDodatneUsluge> ZahtevZaDodatneUsluge { get; set; }
        public virtual DbSet<Zaposleni> Zaposleni { get; set; }
    }
}
