//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFPIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacija()
        {
            this.ZahtevZaDodatneUsluge = new HashSet<ZahtevZaDodatneUsluge>();
        }
    
        public int IDRezervacije { get; set; }
        public System.DateTime DatumDolaska { get; set; }
        public System.DateTime DatumOdlaska { get; set; }
        public int BrojSobe { get; set; }
    
        public virtual Soba Soba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtevZaDodatneUsluge> ZahtevZaDodatneUsluge { get; set; }

        public override string ToString() => $"{IDRezervacije}; {BrojSobe}; {DatumDolaska.ToShortDateString()}-{DatumOdlaska.ToShortDateString()}";
    }
}
