//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFPIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZahtevZaDodatneUsluge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZahtevZaDodatneUsluge()
        {
            this.StavkaZahtevaZaDodatneUsluge = new HashSet<StavkaZahtevaZaDodatneUsluge>();
        }
    
        public int IDZahteva { get; set; }
        public System.DateTime DatumRealizacije { get; set; }
        public int GostID { get; set; }
        public int ZaposleniID { get; set; }
        public int RezervacijaID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Gost Gost { get; set; }
        public virtual Rezervacija Rezervacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaZahtevaZaDodatneUsluge> StavkaZahtevaZaDodatneUsluge { get; set; }
        public virtual Zaposleni Zaposleni { get; set; }
    }
}
